//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizacionApp
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bo.carnesdonfernando.com/", ConfigurationName="ActualizacionApp.ActualizacionSoap")]
    internal interface ActualizacionSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bo.carnesdonfernando.com/actualizarClientePorCedula", ReplyAction="*")]
        System.Threading.Tasks.Task<ActualizacionApp.actualizarClientePorCedulaResponse> actualizarClientePorCedulaAsync(ActualizacionApp.actualizarClientePorCedulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bo.carnesdonfernando.com/actualizarClientePorTarjeta", ReplyAction="*")]
        System.Threading.Tasks.Task<ActualizacionApp.actualizarClientePorTarjetaResponse> actualizarClientePorTarjetaAsync(ActualizacionApp.actualizarClientePorTarjetaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class actualizarClientePorCedulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarClientePorCedula", Namespace="http://bo.carnesdonfernando.com/", Order=0)]
        public ActualizacionApp.actualizarClientePorCedulaRequestBody Body;
        
        public actualizarClientePorCedulaRequest()
        {
        }
        
        public actualizarClientePorCedulaRequest(ActualizacionApp.actualizarClientePorCedulaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bo.carnesdonfernando.com/")]
    internal partial class actualizarClientePorCedulaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ptarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pcedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ptipoCedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pclasificacionCedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pnombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string papellido1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string papellido2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pgenero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pfechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string pdireccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pzona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ptelefono1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ptelefono2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string pcorreo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string pfechaInscripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string psucursal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string penviarCorreo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string penviarMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string pcategoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string pcedulaJurica;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string prazonSocial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string pprovincia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string pcanton;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string pinformacionRecetarios;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string pinformacionCursos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string pinformacionPromociones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string pinfoVisitas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string pacepta_prom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string ppaisNacimiento;
        
        public actualizarClientePorCedulaRequestBody()
        {
        }
        
        public actualizarClientePorCedulaRequestBody(
                    string ptarjeta, 
                    string pcedula, 
                    string ptipoCedula, 
                    string pclasificacionCedula, 
                    string pnombre, 
                    string papellido1, 
                    string papellido2, 
                    string pgenero, 
                    string pfechaNacimiento, 
                    string pdireccion, 
                    string pzona, 
                    string ptelefono1, 
                    string ptelefono2, 
                    string pcorreo, 
                    string pfechaInscripcion, 
                    string psucursal, 
                    string penviarCorreo, 
                    string penviarMensaje, 
                    string pcategoria, 
                    string pcedulaJurica, 
                    string prazonSocial, 
                    string pprovincia, 
                    string pcanton, 
                    string pinformacionRecetarios, 
                    string pinformacionCursos, 
                    string pinformacionPromociones, 
                    string pinfoVisitas, 
                    string pacepta_prom, 
                    string ppaisNacimiento)
        {
            this.ptarjeta = ptarjeta;
            this.pcedula = pcedula;
            this.ptipoCedula = ptipoCedula;
            this.pclasificacionCedula = pclasificacionCedula;
            this.pnombre = pnombre;
            this.papellido1 = papellido1;
            this.papellido2 = papellido2;
            this.pgenero = pgenero;
            this.pfechaNacimiento = pfechaNacimiento;
            this.pdireccion = pdireccion;
            this.pzona = pzona;
            this.ptelefono1 = ptelefono1;
            this.ptelefono2 = ptelefono2;
            this.pcorreo = pcorreo;
            this.pfechaInscripcion = pfechaInscripcion;
            this.psucursal = psucursal;
            this.penviarCorreo = penviarCorreo;
            this.penviarMensaje = penviarMensaje;
            this.pcategoria = pcategoria;
            this.pcedulaJurica = pcedulaJurica;
            this.prazonSocial = prazonSocial;
            this.pprovincia = pprovincia;
            this.pcanton = pcanton;
            this.pinformacionRecetarios = pinformacionRecetarios;
            this.pinformacionCursos = pinformacionCursos;
            this.pinformacionPromociones = pinformacionPromociones;
            this.pinfoVisitas = pinfoVisitas;
            this.pacepta_prom = pacepta_prom;
            this.ppaisNacimiento = ppaisNacimiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class actualizarClientePorCedulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarClientePorCedulaResponse", Namespace="http://bo.carnesdonfernando.com/", Order=0)]
        public ActualizacionApp.actualizarClientePorCedulaResponseBody Body;
        
        public actualizarClientePorCedulaResponse()
        {
        }
        
        public actualizarClientePorCedulaResponse(ActualizacionApp.actualizarClientePorCedulaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bo.carnesdonfernando.com/")]
    internal partial class actualizarClientePorCedulaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool actualizarClientePorCedulaResult;
        
        public actualizarClientePorCedulaResponseBody()
        {
        }
        
        public actualizarClientePorCedulaResponseBody(bool actualizarClientePorCedulaResult)
        {
            this.actualizarClientePorCedulaResult = actualizarClientePorCedulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class actualizarClientePorTarjetaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarClientePorTarjeta", Namespace="http://bo.carnesdonfernando.com/", Order=0)]
        public ActualizacionApp.actualizarClientePorTarjetaRequestBody Body;
        
        public actualizarClientePorTarjetaRequest()
        {
        }
        
        public actualizarClientePorTarjetaRequest(ActualizacionApp.actualizarClientePorTarjetaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bo.carnesdonfernando.com/")]
    internal partial class actualizarClientePorTarjetaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ptarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pcedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ptipoCedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pclasificacionCedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pnombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string papellido1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string papellido2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pgenero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pfechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string pdireccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pzona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ptelefono1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ptelefono2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string pcorreo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string pfechaInscripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string psucursal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string penviarCorreo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string penviarMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string pcategoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string pcedulaJurica;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string prazonSocial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string pprovincia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string pcanton;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string pinformacionRecetarios;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string pinformacionCursos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string pinformacionPromociones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string pinfoVisitas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string pacepta_prom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string ppaisNacimiento;
        
        public actualizarClientePorTarjetaRequestBody()
        {
        }
        
        public actualizarClientePorTarjetaRequestBody(
                    string ptarjeta, 
                    string pcedula, 
                    string ptipoCedula, 
                    string pclasificacionCedula, 
                    string pnombre, 
                    string papellido1, 
                    string papellido2, 
                    string pgenero, 
                    string pfechaNacimiento, 
                    string pdireccion, 
                    string pzona, 
                    string ptelefono1, 
                    string ptelefono2, 
                    string pcorreo, 
                    string pfechaInscripcion, 
                    string psucursal, 
                    string penviarCorreo, 
                    string penviarMensaje, 
                    string pcategoria, 
                    string pcedulaJurica, 
                    string prazonSocial, 
                    string pprovincia, 
                    string pcanton, 
                    string pinformacionRecetarios, 
                    string pinformacionCursos, 
                    string pinformacionPromociones, 
                    string pinfoVisitas, 
                    string pacepta_prom, 
                    string ppaisNacimiento)
        {
            this.ptarjeta = ptarjeta;
            this.pcedula = pcedula;
            this.ptipoCedula = ptipoCedula;
            this.pclasificacionCedula = pclasificacionCedula;
            this.pnombre = pnombre;
            this.papellido1 = papellido1;
            this.papellido2 = papellido2;
            this.pgenero = pgenero;
            this.pfechaNacimiento = pfechaNacimiento;
            this.pdireccion = pdireccion;
            this.pzona = pzona;
            this.ptelefono1 = ptelefono1;
            this.ptelefono2 = ptelefono2;
            this.pcorreo = pcorreo;
            this.pfechaInscripcion = pfechaInscripcion;
            this.psucursal = psucursal;
            this.penviarCorreo = penviarCorreo;
            this.penviarMensaje = penviarMensaje;
            this.pcategoria = pcategoria;
            this.pcedulaJurica = pcedulaJurica;
            this.prazonSocial = prazonSocial;
            this.pprovincia = pprovincia;
            this.pcanton = pcanton;
            this.pinformacionRecetarios = pinformacionRecetarios;
            this.pinformacionCursos = pinformacionCursos;
            this.pinformacionPromociones = pinformacionPromociones;
            this.pinfoVisitas = pinfoVisitas;
            this.pacepta_prom = pacepta_prom;
            this.ppaisNacimiento = ppaisNacimiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class actualizarClientePorTarjetaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarClientePorTarjetaResponse", Namespace="http://bo.carnesdonfernando.com/", Order=0)]
        public ActualizacionApp.actualizarClientePorTarjetaResponseBody Body;
        
        public actualizarClientePorTarjetaResponse()
        {
        }
        
        public actualizarClientePorTarjetaResponse(ActualizacionApp.actualizarClientePorTarjetaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bo.carnesdonfernando.com/")]
    internal partial class actualizarClientePorTarjetaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool actualizarClientePorTarjetaResult;
        
        public actualizarClientePorTarjetaResponseBody()
        {
        }
        
        public actualizarClientePorTarjetaResponseBody(bool actualizarClientePorTarjetaResult)
        {
            this.actualizarClientePorTarjetaResult = actualizarClientePorTarjetaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface ActualizacionSoapChannel : ActualizacionApp.ActualizacionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class ActualizacionSoapClient : System.ServiceModel.ClientBase<ActualizacionApp.ActualizacionSoap>, ActualizacionApp.ActualizacionSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ActualizacionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ActualizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), ActualizacionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActualizacionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ActualizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActualizacionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ActualizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActualizacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ActualizacionApp.actualizarClientePorCedulaResponse> ActualizacionApp.ActualizacionSoap.actualizarClientePorCedulaAsync(ActualizacionApp.actualizarClientePorCedulaRequest request)
        {
            return base.Channel.actualizarClientePorCedulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActualizacionApp.actualizarClientePorCedulaResponse> actualizarClientePorCedulaAsync(
                    string ptarjeta, 
                    string pcedula, 
                    string ptipoCedula, 
                    string pclasificacionCedula, 
                    string pnombre, 
                    string papellido1, 
                    string papellido2, 
                    string pgenero, 
                    string pfechaNacimiento, 
                    string pdireccion, 
                    string pzona, 
                    string ptelefono1, 
                    string ptelefono2, 
                    string pcorreo, 
                    string pfechaInscripcion, 
                    string psucursal, 
                    string penviarCorreo, 
                    string penviarMensaje, 
                    string pcategoria, 
                    string pcedulaJurica, 
                    string prazonSocial, 
                    string pprovincia, 
                    string pcanton, 
                    string pinformacionRecetarios, 
                    string pinformacionCursos, 
                    string pinformacionPromociones, 
                    string pinfoVisitas, 
                    string pacepta_prom, 
                    string ppaisNacimiento)
        {
            ActualizacionApp.actualizarClientePorCedulaRequest inValue = new ActualizacionApp.actualizarClientePorCedulaRequest();
            inValue.Body = new ActualizacionApp.actualizarClientePorCedulaRequestBody();
            inValue.Body.ptarjeta = ptarjeta;
            inValue.Body.pcedula = pcedula;
            inValue.Body.ptipoCedula = ptipoCedula;
            inValue.Body.pclasificacionCedula = pclasificacionCedula;
            inValue.Body.pnombre = pnombre;
            inValue.Body.papellido1 = papellido1;
            inValue.Body.papellido2 = papellido2;
            inValue.Body.pgenero = pgenero;
            inValue.Body.pfechaNacimiento = pfechaNacimiento;
            inValue.Body.pdireccion = pdireccion;
            inValue.Body.pzona = pzona;
            inValue.Body.ptelefono1 = ptelefono1;
            inValue.Body.ptelefono2 = ptelefono2;
            inValue.Body.pcorreo = pcorreo;
            inValue.Body.pfechaInscripcion = pfechaInscripcion;
            inValue.Body.psucursal = psucursal;
            inValue.Body.penviarCorreo = penviarCorreo;
            inValue.Body.penviarMensaje = penviarMensaje;
            inValue.Body.pcategoria = pcategoria;
            inValue.Body.pcedulaJurica = pcedulaJurica;
            inValue.Body.prazonSocial = prazonSocial;
            inValue.Body.pprovincia = pprovincia;
            inValue.Body.pcanton = pcanton;
            inValue.Body.pinformacionRecetarios = pinformacionRecetarios;
            inValue.Body.pinformacionCursos = pinformacionCursos;
            inValue.Body.pinformacionPromociones = pinformacionPromociones;
            inValue.Body.pinfoVisitas = pinfoVisitas;
            inValue.Body.pacepta_prom = pacepta_prom;
            inValue.Body.ppaisNacimiento = ppaisNacimiento;
            return ((ActualizacionApp.ActualizacionSoap)(this)).actualizarClientePorCedulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ActualizacionApp.actualizarClientePorTarjetaResponse> ActualizacionApp.ActualizacionSoap.actualizarClientePorTarjetaAsync(ActualizacionApp.actualizarClientePorTarjetaRequest request)
        {
            return base.Channel.actualizarClientePorTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActualizacionApp.actualizarClientePorTarjetaResponse> actualizarClientePorTarjetaAsync(
                    string ptarjeta, 
                    string pcedula, 
                    string ptipoCedula, 
                    string pclasificacionCedula, 
                    string pnombre, 
                    string papellido1, 
                    string papellido2, 
                    string pgenero, 
                    string pfechaNacimiento, 
                    string pdireccion, 
                    string pzona, 
                    string ptelefono1, 
                    string ptelefono2, 
                    string pcorreo, 
                    string pfechaInscripcion, 
                    string psucursal, 
                    string penviarCorreo, 
                    string penviarMensaje, 
                    string pcategoria, 
                    string pcedulaJurica, 
                    string prazonSocial, 
                    string pprovincia, 
                    string pcanton, 
                    string pinformacionRecetarios, 
                    string pinformacionCursos, 
                    string pinformacionPromociones, 
                    string pinfoVisitas, 
                    string pacepta_prom, 
                    string ppaisNacimiento)
        {
            ActualizacionApp.actualizarClientePorTarjetaRequest inValue = new ActualizacionApp.actualizarClientePorTarjetaRequest();
            inValue.Body = new ActualizacionApp.actualizarClientePorTarjetaRequestBody();
            inValue.Body.ptarjeta = ptarjeta;
            inValue.Body.pcedula = pcedula;
            inValue.Body.ptipoCedula = ptipoCedula;
            inValue.Body.pclasificacionCedula = pclasificacionCedula;
            inValue.Body.pnombre = pnombre;
            inValue.Body.papellido1 = papellido1;
            inValue.Body.papellido2 = papellido2;
            inValue.Body.pgenero = pgenero;
            inValue.Body.pfechaNacimiento = pfechaNacimiento;
            inValue.Body.pdireccion = pdireccion;
            inValue.Body.pzona = pzona;
            inValue.Body.ptelefono1 = ptelefono1;
            inValue.Body.ptelefono2 = ptelefono2;
            inValue.Body.pcorreo = pcorreo;
            inValue.Body.pfechaInscripcion = pfechaInscripcion;
            inValue.Body.psucursal = psucursal;
            inValue.Body.penviarCorreo = penviarCorreo;
            inValue.Body.penviarMensaje = penviarMensaje;
            inValue.Body.pcategoria = pcategoria;
            inValue.Body.pcedulaJurica = pcedulaJurica;
            inValue.Body.prazonSocial = prazonSocial;
            inValue.Body.pprovincia = pprovincia;
            inValue.Body.pcanton = pcanton;
            inValue.Body.pinformacionRecetarios = pinformacionRecetarios;
            inValue.Body.pinformacionCursos = pinformacionCursos;
            inValue.Body.pinformacionPromociones = pinformacionPromociones;
            inValue.Body.pinfoVisitas = pinfoVisitas;
            inValue.Body.pacepta_prom = pacepta_prom;
            inValue.Body.ppaisNacimiento = ppaisNacimiento;
            return ((ActualizacionApp.ActualizacionSoap)(this)).actualizarClientePorTarjetaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActualizacionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ActualizacionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActualizacionSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8180/TM-PROD-01/Actualizacion.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ActualizacionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8180/TM-PROD-01/Actualizacion.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ActualizacionSoap,
            
            ActualizacionSoap12,
        }
    }
}
